"""Native optimization contracts for guarded dispatch and scalar proofs."""

from atoll.native_optimization.models import (
    BindingDispatchPlan,
    BufferLayoutGuardPayload,
    CallableCodeIdentityGuardPayload,
    CompiledBindingVariant,
    CompiledVariantKind,
    DirectFieldGuardPayload,
    DispatchTargetKind,
    ExactTypeGuardPayload,
    GuardExpression,
    GuardKind,
    GuardPayload,
    IntegerBitWidth,
    IntegerDomainGuardPayload,
    NativeVariantPlan,
    stable_native_variant_plan_id,
)
from atoll.native_optimization.scalar_analysis import (
    ScalarAnalysisResult,
    ScalarKernelPlan,
    ScalarMemberAnalysisOptions,
    ScalarOperationRecord,
    ScalarParameterDomain,
    ScalarRejection,
    ScalarWidthProof,
    analyze_scalar_member,
    analyze_scalar_scan,
)

__all__ = (
    "BindingDispatchPlan",
    "BufferLayoutGuardPayload",
    "CallableCodeIdentityGuardPayload",
    "CompiledBindingVariant",
    "CompiledVariantKind",
    "DirectFieldGuardPayload",
    "DispatchTargetKind",
    "ExactTypeGuardPayload",
    "GuardExpression",
    "GuardKind",
    "GuardPayload",
    "IntegerBitWidth",
    "IntegerDomainGuardPayload",
    "NativeVariantPlan",
    "ScalarAnalysisResult",
    "ScalarKernelPlan",
    "ScalarMemberAnalysisOptions",
    "ScalarOperationRecord",
    "ScalarParameterDomain",
    "ScalarRejection",
    "ScalarWidthProof",
    "analyze_scalar_member",
    "analyze_scalar_scan",
    "stable_native_variant_plan_id",
)
