"""Generate pure-Python Atoll sidecar modules."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

from atoll.models import (
    ConstantRecord,
    DependencyEdge,
    EnabledIslandConfig,
    ImportRecord,
    ModuleScan,
    SidecarGeneration,
    SymbolId,
    SymbolRecord,
)

_GENERATOR_VERSION = "atoll-sidecar-v1"


@dataclass(frozen=True, slots=True)
class SidecarPlan:
    """Concrete source fragments copied into a generated sidecar."""

    imports: tuple[ImportRecord, ...]
    constants: tuple[ConstantRecord, ...]
    symbols: tuple[SymbolRecord, ...]
    included_symbol_names: tuple[str, ...]
    copied_sources: tuple[str, ...]


def generate_sidecar(module: ModuleScan, config: EnabledIslandConfig) -> SidecarGeneration:
    """Generate a pure-Python sidecar for `config` from a scanned source module."""
    plan = build_sidecar_plan(module, config.symbols)
    source_hash = _source_hash(plan, config)
    source = _render_sidecar(config, plan, source_hash)
    return SidecarGeneration(
        config=config,
        included_symbols=plan.included_symbol_names,
        source_hash=source_hash,
        source_text=source,
    )


def write_sidecar(generation: SidecarGeneration) -> None:
    """Write a generated sidecar source file."""
    generation.config.sidecar_path.parent.mkdir(parents=True, exist_ok=True)
    generation.config.sidecar_path.write_text(generation.source_text, encoding="utf-8")


def build_sidecar_plan(
    module: ModuleScan,
    exported_symbols: tuple[str, ...],
) -> SidecarPlan:
    """Select imports, constants, and symbols required for a sidecar."""
    top_level_functions = {
        symbol.id.qualname: symbol for symbol in module.symbols if symbol.kind == "function"
    }
    _validate_exported_symbols(exported_symbols, top_level_functions)
    included_names = _expand_included_symbols(exported_symbols, module.dependency_edges)
    included_symbols = tuple(
        symbol
        for symbol in sorted(top_level_functions.values(), key=lambda item: item.lineno)
        if symbol.id.qualname in included_names
    )
    referenced_names = {name for symbol in included_symbols for name in symbol.referenced_names}
    imports = tuple(
        record
        for record in module.imports
        if record.source_text == "from __future__ import annotations"
        or any(name in referenced_names for name in record.imported_names)
    )
    constants = tuple(
        constant
        for constant in module.constants
        if constant.name in referenced_names and constant.kind == "literal_constant"
    )
    source_lines = module.module.path.read_text(encoding="utf-8").splitlines()
    return SidecarPlan(
        imports=imports,
        constants=constants,
        symbols=included_symbols,
        included_symbol_names=tuple(symbol.id.qualname for symbol in included_symbols),
        copied_sources=tuple(
            "\n".join(source_lines[symbol.lineno - 1 : symbol.end_lineno])
            for symbol in included_symbols
        ),
    )


def default_sidecar_module(source_module: str) -> str:
    """Return Atoll's default sidecar module name for a source module."""
    package, _, module_name = source_module.rpartition(".")
    sidecar_name = f"_{module_name}_atoll"
    return f"{package}.{sidecar_name}" if package else sidecar_name


def expected_sidecar_path(module: ModuleScan, sidecar_module: str) -> Path:
    """Return the source path for a sidecar next to its source module."""
    return module.module.path.parent / f"{sidecar_module.rsplit('.', maxsplit=1)[-1]}.py"


def _validate_exported_symbols(
    exported_symbols: tuple[str, ...],
    top_level_functions: dict[str, SymbolRecord],
) -> None:
    unknown = tuple(symbol for symbol in exported_symbols if symbol not in top_level_functions)
    if unknown:
        raise ValueError(f"unknown top-level function symbols: {', '.join(unknown)}")


def _expand_included_symbols(
    exported_symbols: tuple[str, ...],
    edges: tuple[DependencyEdge, ...],
) -> set[str]:
    included = set(exported_symbols)
    changed = True
    while changed:
        changed = False
        for edge in edges:
            if edge.kind != "calls" or not isinstance(edge.dst, SymbolId):
                continue
            if edge.src.qualname in included and edge.dst.qualname not in included:
                included.add(edge.dst.qualname)
                changed = True
    return included


def _render_sidecar(
    config: EnabledIslandConfig,
    plan: SidecarPlan,
    source_hash: str,
) -> str:
    lines = [
        "# This file is generated by Atoll. Do not edit manually.",
        f"# Source module: {config.source_module}",
        f"# Exported symbols: {', '.join(config.symbols)}",
        f"# Source hash: {source_hash}",
        "",
    ]
    if not any(
        record.source_text == "from __future__ import annotations" for record in plan.imports
    ):
        lines.append("from __future__ import annotations")
    lines.extend(record.source_text for record in plan.imports)
    if plan.imports or lines[-1] != "":
        lines.append("")
    lines.extend(constant.source_text for constant in plan.constants)
    if plan.constants:
        lines.append("")
    for copied_source in plan.copied_sources:
        lines.extend(copied_source.splitlines())
        lines.append("")
    lines.extend(
        [
            "__atoll_metadata__ = {",
            f'    "source_module": "{config.source_module}",',
            f'    "sidecar_module": "{config.sidecar_module}",',
            f'    "exported_symbols": {tuple(config.symbols)!r},',
            f'    "included_symbols": {plan.included_symbol_names!r},',
            f'    "source_hash": "{source_hash}",',
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def _source_hash(plan: SidecarPlan, config: EnabledIslandConfig) -> str:
    digest = hashlib.sha256()
    digest.update(_GENERATOR_VERSION.encode())
    digest.update(config.source_module.encode())
    digest.update(config.sidecar_module.encode())
    for record in plan.imports:
        digest.update(record.source_text.encode())
    for constant in plan.constants:
        digest.update(constant.source_text.encode())
    for symbol in plan.symbols:
        digest.update(symbol.id.qualname.encode())
    for copied_source in plan.copied_sources:
        digest.update(copied_source.encode())
    return digest.hexdigest()
